#!/bin/sh
set -eu

root=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
source_file=$root/codex-meter

if [ -n "${CODEX_METER_BIN_DIR:-}" ]; then
    bindir=$CODEX_METER_BIN_DIR
elif [ -n "${PREFIX:-}" ] && [ -d "${PREFIX}/bin" ]; then
    bindir=$PREFIX/bin
else
    bindir=$HOME/.local/bin
fi

python_cmd=${CODEX_METER_PYTHON:-}
if [ -z "$python_cmd" ]; then
    python_cmd=$(command -v python3 || command -v python || true)
fi

if [ -z "$python_cmd" ]; then
    printf '%s\n' 'codex-meter: Python is not installed; skipping wrapper install' >&2
    exit 0
fi

mkdir -p "$bindir"
wrapper=$bindir/codex-meter
tmp=$bindir/.codex-meter.tmp.$$

{
    printf '%s\n' '#!/bin/sh'
    printf '%s\n' '# generated by codex-meter/install.sh'
    printf 'exec "%s" "%s" "$@"\n' "$python_cmd" "$source_file"
} > "$tmp"
chmod 0755 "$tmp"
mv "$tmp" "$wrapper"

printf 'codex-meter -> %s\n' "$source_file"
printf 'installed wrapper: %s\n' "$wrapper"
